### ISSUE TITLE
Max Guests regex

### ISSUE THREAD

**Issue by ikedaandre** [romanrosh/airbnb-web-scaper#1]
The regex for max guests seems to be failing:

max_guests = int(re.sub(self.REGEX_3, '', soup.find_all(attrs={'class': '_6mxuijo'})[0].text))
ValueError: invalid literal for int() with base 10: ''

**Comment by romanrosh** [comment]
> The regex for max guests seems to be failing:
> 
> max_guests = int(re.sub(self.REGEX_3, '', soup.find_all(attrs={'class': '_6mxuijo'})[0].text))
> ValueError: invalid literal for int() with base 10: ''

Thanks for checking out the project!
Since classes are changed per each request in html the code samples the classes hence the error messages, it does not affect the outcome just continue the program execution.
Hope it works out let me know if there are other issues!
